### PR TITLE
Update Code Organization

### PR DESCRIPTION
**Pull request by DavisHenckel**
## Main Changes
No more Client.Code Namespace. Instead, this has been separated to mutliple different folders with a more specific purpose. Below I have listed a description of the new structure, their namespaces, and the intended purpose. 
### Client.Crypto
This will be the place for the core of all our cryptography algorithms.
### Client.Services
This will contain different services or utlities that the client needs. Currently the files residing in this folder are:
- FileUtil -> renamed to FileUtilService
- Cryptography -> renamed to EncryptionService 
- New file to be built for managing account services called AccountService
- BouncyCastleHashing -> renamed to HashingService
- WebClient -> renamed to HttpService
### Client.Components
This was already a folder, but it used to be Client.Components.Public.Shared. I removed the nested folders.
### Pages
This already existed, it hasn't changed other than the SignUp and SignIn pages now have corresponding code behind pages. They previously existed in Client.Code.
### Models
This is a folder for the classes that are used in our client project. The current files residing in this folder are:
- EncFile
- TransferMeUser
- SignInRequest (might remove later, not sure)
### ViewModels
From my research, this is a good practice for classes that are used on the front end and displayed to the user, the only file in this folder currently is a class SignUpVM (VM for view model) it contains the fields and the validation needed for the sign-up form.

## Final Notes
- MainLayout.razor now has a corresponding code behind page that was previously the Drawer class.
-  I tested uploading files and user credentials to the database, navigated to all web pages, and everything is working. 
- Removed Shared Project since it was not being used.

Hopefully this structure makes sense to you all and ideally this will speed up our remaining development for the year.

### CODE REVIEW

**Comment by DavisHenckel** [comment]
[Reorganize/Refactor Code](https://trello.com/c/b6qjMIBZ/55-reorganize-refactor-code)

**Comment by hassansh90** [comment]
I like it. The code needed some organization

**Comment by DavisHenckel** [comment]
[Fix Shared Models](https://trello.com/c/qXrWiOfv/53-fix-shared-models)

**Comment by DavisHenckel** [comment]
[Move Client Code to code behind file](https://trello.com/c/1aAg32xZ/52-move-client-code-to-code-behind-file)

**Comment by DavisHenckel** [comment]
[Remove all instances of Azure Key in Version control](https://trello.com/c/v755PIQe/67-remove-all-instances-of-azure-key-in-version-control)

**Pull request merged**
