### PR TITLE
Theming update

### PR DESCRIPTION
**Pull request by DavisHenckel**
## Theming Update
Finally have something to show for the hours of research and work I spent trying to get the theme's to function. It's not entirely completed, there is only one piece to go. Right now the Theme stays on the about page, but each time the Home page is loaded it is re-rendered and set back to light theme each time.

### Summary of changes
- Added a Theme's folder
- Removed unnecessary call to MudThemeProvider in App.razor (this is what was causing Theme's to not work) 
- Re-built the code behind file in MainLayout.razor
- Made light theme Orange/White/Black
- Made dark theme Orange/Black/White
- Removed Navbar and Fixed small window sizes making the app unresponsive
- Added some icons to the upload and clear buttons
- updated the About page and made the Title button a link back to the "/" route.

### CODE REVIEW

**Comment by DavisHenckel** [comment]
[Implement new Theming across the app](https://trello.com/c/8JrfksnU/101-implement-new-theming-across-the-app)

**Comment by DavisHenckel** [comment]
[Incorporate more Icons for better accessibility](https://trello.com/c/DOkrL8ru/102-incorporate-more-icons-for-better-accessibility)

**Comment by DavisHenckel** [comment]
[Remove NavBar](https://trello.com/c/R2KoBUUA/103-remove-navbar)

**Comment by DavisHenckel** [comment]
[Fix issue of small window sizes breaking app](https://trello.com/c/m634hu5F/60-fix-issue-of-small-window-sizes-breaking-app)

**Comment by DavisHenckel** [comment]
[Fix Navbar scaling issue](https://trello.com/c/hNnPK10V/62-fix-navbar-scaling-issue)

**Review by AlexGrasley — APPROVED** [review]

**Pull request merged**
