### PR TITLE
Security code cleanup & Front End Enhancement

### PR DESCRIPTION
**Pull request by DavisHenckel**
## Changes
- Regenerated keys in Azure and got the DB connection working. Verified File uploads and user credentials work as they did before. (Instructions below)
- Created About Page Content
image
- Created Profile Page Content
image
- Removed unnecessary JSON serialization of Context and used the built in Method I built my ViewModel for. (Thanks Alex)

## How to Setup the new database connection.
Since our active keys are no longer in source code, we have to manually configure the connection to our database one time. I read some of the documentation here and it explained it succinctly. https://docs.microsoft.com/en-us/aspnet/core/security/app-secrets?view=aspnetcore-6.0&tabs=windows

There is a file secrets.json that interacts with our server project. It is stored in your Window's profile's appdata at %APPDATA%\Microsoft\UserSecrets\

We can access it using the code that is now pushed once the secrets file is updated.

### Steps to Setup the DB Connection.
- Navigate to the keys section of our Cosmos DB Service
image
- Copy the Primary Key and the URI in the web portal
- Right Click the Server Project in Visual Studio and select Manage User Secrets
- Make sure Keys are exactly named this
image
- Save the file and verify connection.

### CODE REVIEW

**Comment by DavisHenckel** [comment]
[Remove all instances of Azure Key in Version control](https://trello.com/c/v755PIQe/67-remove-all-instances-of-azure-key-in-version-control)

**Comment by DavisHenckel** [comment]
[Refactor Instantiation of TransferMeUser](https://trello.com/c/OGOpgCEu/80-refactor-instantiation-of-transfermeuser)

**Comment by DavisHenckel** [comment]
[Fill Out About Page](https://trello.com/c/1SIRymtC/64-fill-out-about-page)

**Comment by DavisHenckel** [comment]
[Fill Out Profile Page](https://trello.com/c/myoqWuck/28-fill-out-profile-page)

**Review by AlexGrasley — APPROVED** [review]
looks fine to me

**Pull request merged**
